version: '3'

services:
  sample-db:
    container_name: sample-db
    image: mysql:8
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: passw0rd
      MYSQL_DATABASE: sample_db
      MYSQL_USER: sample_user
      MYSQL_PASSWORD: passw0rd
    ports:
      - '3306:3306'
    expose:
      - '3306'
    network_mode: "host"
  sample-api:
    container_name: sample-api
    build: .
    environment:
      - FLASK_ENV=development
    volumes:
      - .:/opt
    command: ["/wait-for-it.sh", "-s", "-t", "0", "localhost:3306", "--", "sh", "/opt/sample/bootstrap.sh"]
    depends_on:
      - sample-db
    network_mode: "host"
  sample-ui:
    container_name: sample-ui
    build:
      context: .
      dockerfile: ./sample-ui/Dockerfile
    volumes:
      - .:/opt
    command: ["/wait-for-it.sh", "-s", "-t", "0", "localhost:5000", "--", "sh", "/opt/sample-ui/bootstrap.sh"]
    depends_on:
      - sample-api
    network_mode: "host"
  sample-web:
    container_name: sample-web
    build:
      context: .
      dockerfile: ./Dockerfile_nginx
    volumes:
     - ./etc/nginx/sample.docker.template:/etc/nginx/conf.d/sample.docker.template
    ports:
     - "80:80"
    environment:
     - NGINX_PORT=80
    command: ["/wait-for-it.sh", "-s", "-t", "0", "localhost:5000", "--", "sh", "/nginx_config.sh"]
    depends_on:
      - sample-api
      - sample-ui
    network_mode: "host"
volumes:
  db_data:
